### PR TITLE
Todo App Code Review Request

### PR DESCRIPTION
**Pull request by teekaytech**
# This Review Request showcases my implementation of the Todo List application :smile: 

## Here's the summary of activities carried out:
- I was able to use webpack for project setup and dependencies management.
- I used ES6 objects/classes as introduced in the previous lesson.
- I also implemented the basic specifications as highlighted by TOP 

**Kindly review the project for approval** :man_technologist:

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @teekaytech 
### You have done good so far :clap: However, you have a few issues that you need to fix:-
- [x] Add `.stylelintrc.json` and `.eslintrc.json` as recommended and ensure it passes any error it might return, [follow this link](https://github.com/microverseinc/linters-config/tree/master/javascript)
- [x] Remove the alert message and replace it with inline message, either via a paragraph or a heading
- [x] Also, modify your scripts in package.json to look like below:
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Comment by teekaytech** [comment]
## Hi,

### I've made the changes required above. Kindly re-check for approval. :blush:

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Requested changes :recycle: :traffic_light: 

Hi @teekaytech, great job implementing the changes outlined by the previous TSE :+1: However, after cloning and running the project on my system, I got the following error:smile: 
- This error came as a result of running `npm start`. So I was presented with an empty page, only the background I could see. So I decided to check the browser console. Kindly find the error below
cn
Kindly check and fix this issue
Once this is fixed, kindly submit another code review :slightly_smiling_face: 

_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by teekaytech** [comment]
### Hello there :wave: 

**I've fixed the error raised above. Kindly review my project for approval :man:**

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED

Hi @teekaytech you have done really well working on this project, it looks really nice fro the live version, but there is still some problem running it locally? did you deploy the latest changes :thinking: 
I get a blank page and an error in the console when I try to run it, see screenshot below

blankpage

**Please make changes and request for another review when you are done** :+1:  

**RAPHAEL NORIODE** :mask: STAY_SAFE

**Comment by teekaytech** [comment]
### Hello, 

I've been able to remove this bug. Kindly check for approval.

**Review by mosesogwo — APPROVED** [review]
### Hello:wave: @teekaytech, Nice work. Project is approved :heavy_check_mark:

**Pull request merged**
